---
- name: Install EPEL repo
  apt:
    name=epel-release
    state=present

- name: Install nginx server
  apt:
    name=nginx
    enablerepo=epel
    state=present

- name: Start nginx
  service:
    name=nginx
    state=started
    enabled=yes

- name: Update nginx default config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - Test nginx configuration
    - Reload nginx configuration

- name: Update nginx site config
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify:
    - Test nginx configuration
    - Reload nginx configuration

- name: Get application path content
  shell: ls -1 /var/www/html/
  register: content

- name: Delete all file in path
  file: path=/var/www/html/{{item}} state=absent
  with_items: "{{content.stdout_lines}}"

- name: Update siteweb
  copy: src=index.php dest=/var/www/html/index.php
  notify:
    - Test nginx configuration
    - Reload nginx configuration
