---
#- name: Install EPEL repo

- name: Install php
  apt:
    name=php
    state=present

- name: Install nginx server
  apt:
    name=apache2
    state=present

- name: Update conf
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf

- name: Restart service apache2, in all cases
  service:
    name: apache2
    state: restarted

- name: Get application path content
  shell: ls -1 /var/www/html/
  register: content

- name: Delete all file in path
  file: path=/var/www/html/{{item}} state=absent
  with_items: "{{content.stdout_lines}}"

- name: Update siteweb
  #copy: src=index.php dest=/var/www/html/index.php
  template: src=index.php.j2 dest=/var/www/html/index.php
